import Header from "./components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Landing from "./landing";
import MySkills from "./myskills";
import Gallery from "./gallery";
import Certifications from "./components/Certifications";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {/* {children} */}
        <Landing />
        <MySkills />
        <Certifications />
        {/* <Gallery /> */}
      </body>
    </html>
  );
}
