import Header from "./components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Landing from "./landing";
import MySkills from "./myskills";
import Gallery from "./gallery";
import Certifications from "./components/Certifications";
import Technology from "./technology";
import Numbers from "./numbers";
import Experience from "./experience";
import Footer from "./footer";
import Anime from "./anime";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-indigo-400 to-cyan-400 w-full">
        <Header />
        {/* {children} */}
        <Landing />
        <MySkills />
        <Certifications />
        <Technology />
        <Numbers />
        <Experience />
        <Footer />
        <Anime />
      </body>
    </html>
  );
}
